name: CI based on Polyhal template
on: 
  push:
  pull_request:
  workflow_dispatch:

jobs:
  template:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, riscv64, aarch64, loongarch64]
        include:
          - arch: aarch64
            packages: qemu-system-aarch64
          - arch: riscv64
            packages: qemu-system-riscv
          - arch: x86_64
            packages: qemu-system-x86
          - arch: loongarch64
            packages: qemu-system-loongarch64
    steps:
      - uses: actions/checkout@v4
        with:
          path: 'template'
      - name: Install generaic tools
        run: yes | pacman -Syy make cmake rustup gcc git libgit2 libgit2-glib pkgconf openssl
      - name: Install Rust toolchain
        run: rustup default stable && cargo install cargo-binutils && cargo install cargo-generate
      - name: generate by template
        run: USER=test cargo generate --path template -n test-polyhal
      - name: Install Qemu
        run: yes | pacman -Syy ${{ matrix.packages }}
      - name: test run
        run: cd test-polyhal && PATH=$PATH:~/.cargo/bin timeout 40 make ARCH=${{ matrix.arch }} run > output.log
      - name: test log
        run: grep "\[kernel\] exited successfully" output.log
